"""added email confirmation

Revision ID: a9f3b76b09e9
Revises: 368d4f806360
Create Date: 2024-07-03 18:34:55.614326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9f3b76b09e9'
down_revision: Union[str, None] = '368d4f806360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_confirmation_token', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email_confirmation_token'), 'users', ['email_confirmation_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email_confirmation_token'), table_name='users')
    op.drop_column('users', 'email_confirmation_token')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
